<pre class="metadata">
Title: Python language binding for WebIDL
Shortname: webidl-python
Status: LS
TR: https://jcbhmr.github.io/webidl-python/
URL: https://jcbhmr.github.io/webidl-python/
Repository: jcbhmr/webidl-python
Editor: Jacob Hummer, jcbhmr@outlook.com, https://jcbhmr.me/
Markup Shorthands: markdown yes
Abstract: 🐍 WebIDL types ↔️ Python types
</pre>

<pre class="include">path: intro.bs</pre>

